### ISSUE TITLE
creating the database & table using mysql package

### ISSUE THREAD

**Issue by ebraj** [ebraj/MovieHub#1]
### Tasks :
1. Create the schema from the ER diagram.
2. Create the tables referencing the schema.

**Comment by Dikshyantaaryal** [comment]
nice will do

**Comment by ebraj** [comment]
Markdown guide - https://itsfoss.com/markdown-guide/

**Comment by chhetri123** [comment]
All the best guys .Just stalking to your project 😆

**Comment by ebraj** [comment]
Thank you @chhetri123 for stalking. That's what makes us(me and @Dikshyantaaryal) motivated for doing this project😝.
